apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: application-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: application
      app.kubernetes.io/name: helm
  template:
    metadata:
      labels:
        app: application-canary
    spec:
      containers:
        - env:
            - name: AppVersion
              value: 1.16.14
          image: 'tonybaqain/node-hello:1.16.14'
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          name: -canary
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext: {}
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 30
      - setWeight: 20
      - pause: {} # pause indefinitely